INSERT INTO object_alcohol VALUES(WineType('Abadia Retuerta Seleccion Especial',1,750,'Abadia Retuerta',11.5,'Spain','Sardon De Duero',2007,3.938));
INSERT INTO object_alcohol VALUES(WineType('Aardvark Cameros Pinot Noir',2,750,'Aardvark',12.5,'France','Pinot Noir',2005,4.292));
INSERT INTO object_alcohol VALUES(WineType('Abbaye Saint Hilarie Cuvee du Prieur',3,750,'Abbaye Saint',12,'France','Bordeaux',2006,4.212));
INSERT INTO object_alcohol VALUES(WineType('Acinum Chianti DOCG',4,750,'Acinum',11.75,'Italy','Sangiovese',2009,3.437));
INSERT INTO object_alcohol VALUES(WineType('Altesino Brunello di Montalcino',5,750,'Altesino',11.9,'Italy','Brunello',2005,4.558));
INSERT INTO object_alcohol VALUES(WineType('Adega de Pegoes Red',6,750,'Adega de Pegoes',12.5,'Spain','Red',2007,3.582));
INSERT INTO object_alcohol VALUES(WineType('Alfredo Prunotto Barolo Bussia',7,750,'Alfredo Prunotto',12.5,'Italy','Nebbiolo',2001,4.692));
INSERT INTO object_alcohol VALUES(WineType('Allegrini Amarone Classico',8,750,'Amarone',12,'Italy','Red',2005,4.421));
INSERT INTO object_alcohol VALUES(WineType('Alma Rosa Pinot Noir',750,9,'Alma Rosa',11.4,'America','Pinot Noir',2006,4.358));
INSERT INTO object_alcohol VALUES(WineType('Altesino Brunello di Montalcino Riserva',10,750,'Altesino',11,'Italy','Brunello',2003,4.582));
INSERT INTO object_alcohol VALUES(LiquorType('The Lash Spiced Rum',11,750,'The Lash',35,'Brazil','Rum',2010,4.056));
INSERT INTO object_alcohol VALUES(LiquorType('Dewars Signature Blend',12,750,'Dewars',43,'Ireland','Scotch',2001,4.219));
INSERT INTO object_alcohol VALUES(LiquorType('Johnnie Walker Black Label',13,750,'Johnnie Walker',43,'Scotland','Scotch',1996,4.551));
INSERT INTO object_alcohol VALUES(LiquorType('Don Julio Silver',14,750,'Don Julio',40,'Spain','Tequila',2005,4.651));
INSERT INTO object_alcohol VALUES(LiquorType('Bakon Vodka',15,750,'Black Rock Spirits',40,'America','Vodka',2010,4.912));
INSERT INTO object_alcohol VALUES(LiquorType('Grey Goose Vodka',16,750,'Grey Goose',40,'France','Vodka',2010,4.652));
INSERT INTO object_alcohol VALUES(LiquorType('Elmer T. Lee Single Barrel Bourbon',17,750,'Elmer T. Lee',45,'Ireland','Whiskey',2005,4.132));
INSERT INTO object_alcohol VALUES(LiquorType('Alexander Platinum Grappa Veneto',18,750,'Alexander',40,'Italy','Brandy',2010,4.56));
INSERT INTO object_alcohol VALUES(LiquorType('Bauchant Orange Liqueur France',19,750,'Bauchant',20,'France','Cognac',2009,4.102));
INSERT INTO object_alcohol VALUES(LiquorType('Tub Dry Gin',20,750,'Tub',40,'America','Gin',2010,3.919));
INSERT INTO object_alcohol VALUES(LiquorType('10 Cane Rum',21,750,'10 Cane',40,'Jamaica','Rum',2011,4.19));
INSERT INTO object_alcohol VALUES(BeerType('Red Dog',22,12,'Miller',5,'America',130,'Lager',3.543));
INSERT INTO object_alcohol VALUES(BeerType('Molson XXX',23,12,'Molson',4.8,'Canada',120,'Lager',3.913));
INSERT INTO object_alcohol VALUES(BeerType('Bass Ale',24,12,'Bass Brewery',4.9,'England',125,'Ale',4.032));
INSERT INTO object_alcohol VALUES(BeerType('Carlsberg Elephant',25,12,'Carlsberg Group',5,'Denmark',140,'Lager',4.123));
INSERT INTO object_alcohol VALUES(BeerType('Fischer Amber',26,12,'Heinken',6,'France',135,'Lager',4.346));
INSERT INTO object_alcohol VALUES(BeerType('Becks',27,12,'Becks Brewery',5,'Germany',130,'Pale Lager',4.132));
INSERT INTO object_alcohol VALUES(BeerType('Schneider Weisse Original',28,12,'Schneider Weisse',5.4,'Germany',130,'Ale',4.231));
INSERT INTO object_alcohol VALUES(BeerType('Kingfischer Lager',29,12,'United Breweries Group',5,'India',120,'Lager',4.321));
INSERT INTO object_alcohol VALUES(BeerType('Sapporo Draft',30,12,'Sapporo Brewery',4.9,'Japan',125,'Lager',4.172));
INSERT INTO object_alcohol VALUES(BeerType('Corona',31,12,'Cerveceria Modelo',4.6,'Mexico',120,'Light',3.98));
INSERT INTO object_alcohol VALUES(WDrinkType('Smirnoff Ice Triple Black',32,12,'Diageo',4.5,'England',220,'Lime',4.135));
INSERT INTO object_alcohol VALUES(WDrinkType('Smirnoff Ice Watermelon',33,12,'Diageo',4.5,'England',215,'Watermelon',4.612));
INSERT INTO object_alcohol VALUES(WDrinkType('Smirnoff Ice Pomegranate',34,12,'Diageo',5.5,'England',220,'Pomegranate',3.819));
INSERT INTO object_alcohol VALUES(WDrinkType('Smirnoff Black Ice',35,12,'Diageo',7,'England',220,'Blackberry',4.192));
INSERT INTO object_alcohol VALUES(WDrinkType('Smirnoff Ice Raspberry Burst',36,12,'Diageo',5,'England',225,'Raspberry',3.913));
INSERT INTO object_alcohol VALUES(WDrinkType('Mikes Hard Lemonade',37,12,'Mikes Hard Lemonade Co.',5,'America',222,'Lemonade',3.991));
INSERT INTO object_alcohol VALUES(WDrinkType('Mikes Harder Lemonade',38,12,'Mikes Hard Lemonade Co.',8,'America',230,'Lemonade',4.155));
INSERT INTO object_alcohol VALUES(WDrinkType('Mikes Mike-arita',39,12,'Mikes Hard Lemonade Co.',10,'America',225,'Lime',4.231));
INSERT INTO object_alcohol VALUES(WDrinkType('Mikes Hard Mango Punch',40,12,'Mikes Hard Lemonade Co.',5.5,'America',225,'Mango',4.291));
INSERT INTO object_alcohol VALUES(WDrinkType('Mikes Hard Fruit Punch',41,12,'Mikes Hard Lemonade Co.',5.5,'America',225,'Fruit Punch',4.173));

INSERT INTO object_stores VALUES('International Wine and Spirits','Mon-Sat: 11:00 am - 10:00 pm','Liquor Store',AddressType('2903 Broadway','New York','NY','10025'));
INSERT INTO object_stores VALUES('Jiminez Ramon','Mon-Sat: 11:00 am - 10:00 pm','Liquor Store',AddressType('3139 Broadway','New York','NY','10027'));
INSERT INTO object_stores VALUES('Morton Williams','24/7','Grocery Store',AddressType('2941 Broadway','New York','NY','10027'));
INSERT INTO object_stores VALUES('Apple Tree Supermarket','24/7','Grocery Store',AddressType('1225 Amsterdam Avenue','New York','NY','10027'));
INSERT INTO object_stores VALUES('Gourmet Deli Inc','24/7','Deli',AddressType('990 Amsterdam Avenue','New York','NY','10025'));

INSERT INTO object_sold_at VALUES(2,1,1,22.99);
INSERT INTO object_sold_at VALUES(22,3,6,14.99);
INSERT INTO object_sold_at VALUES(24,5,6,14.99);
INSERT INTO object_sold_at VALUES(31,4,6,35.99);
INSERT INTO object_sold_at VALUES(8,2,1,40.99);
INSERT INTO object_sold_at VALUES(1,1,1,80.99);
INSERT INTO object_sold_at VALUES(30,2,6,12.99);
INSERT INTO object_sold_at VALUES(31,3,6,10.99);
INSERT INTO object_sold_at VALUES(5,4,1,15.99);
INSERT INTO object_sold_at VALUES(25,5,6,11.99);
INSERT INTO object_sold_at VALUES(6,1,1,14.99);
INSERT INTO object_sold_at VALUES(11,2,1,35.99);
INSERT INTO object_sold_at VALUES(14,3,1,23.99);
INSERT INTO object_sold_at VALUES(18,4,1,21.99);
INSERT INTO object_sold_at VALUES(11,5,1,31.99);
INSERT INTO object_sold_at VALUES(12,1,1,41.99);
INSERT INTO object_sold_at VALUES(17,2,1,52.99);
INSERT INTO object_sold_at VALUES(3,3,1,44.99);
INSERT INTO object_sold_at VALUES(13,4,1,40.99);
INSERT INTO object_sold_at VALUES(18,5,1,30.99);
INSERT INTO object_sold_at VALUES(15,1,1,71.99);
INSERT INTO object_sold_at VALUES(20,2,1,20.99);

INSERT INTO object_account VALUES(0,'ninjaturtles','p4ssw0rd','abc@gmail.com');
INSERT INTO object_account VALUES(1,'sexytime','bestPASSWORDever!1!','def@gmail.com');
INSERT INTO object_account VALUES(0,'friday','letmein!','ghi@gmail.com');
INSERT INTO object_account VALUES(0,'ragingbull','abc123','jkl@gmail.com');
INSERT INTO object_account VALUES(0,'mysticshadow','Iamabanana','mno@gmail.com');
INSERT INTO object_account VALUES(0,'trollolol','weeeeeee!!','pqr@gmail.com');
INSERT INTO object_account VALUES(1,'babycakes','iLoveThisSite','stu@gmail.com');
INSERT INTO object_account VALUES(0,'newuser','youllneverguessthis','vwx@gmail.com');
INSERT INTO object_account VALUES(0,'bigdaddy','hahahayeah','yandz@gmail.com');
INSERT INTO object_account VALUES(0,'cookiemonster','imadeapassword','nomoreletters@gmail.com');

INSERT INTO object_bought VALUES('ninjaturtles',to_date('2000/01/23:12:00:00AM', 'yyyy/mm/dd:hh:mi:ssam'),2,1,1,22.99);
INSERT INTO object_bought VALUES('sexytime',to_date('2010/02/21:12:00:00AM', 'yyyy/mm/dd:hh:mi:ssam'),22,3,6,14.99);
INSERT INTO object_bought VALUES('sexytime',to_date('2009/01/23:10:00:00PM', 'yyyy/mm/dd:hh:mi:ssam'),24,5,6,14.99);
INSERT INTO object_bought VALUES('ragingbull',to_date('2011/03/18:11:32:00AM', 'yyyy/mm/dd:hh:mi:ssam'),31,4,6,35.99);
INSERT INTO object_bought VALUES('ragingbull',to_date('2009/02/11:02:11:20AM', 'yyyy/mm/dd:hh:mi:ssam'),1,1,1,80.99);
INSERT INTO object_bought VALUES('cookiemonster',to_date('2008/08/02:03:23:12PM', 'yyyy/mm/dd:hh:mi:ssam'),8,2,1,40.99);
INSERT INTO object_bought VALUES('friday',to_date('2008/09/22:02:53:23PM', 'yyyy/mm/dd:hh:mi:ssam'),5,4,1,15.99);
INSERT INTO object_bought VALUES('mysticshadow',to_date('2010/08/12:03:43:12AM', 'yyyy/mm/dd:hh:mi:ssam'),14,3,1,23.99);
INSERT INTO object_bought VALUES('cookiemonster',to_date('2009/06/22:04:13:12PM', 'yyyy/mm/dd:hh:mi:ssam'),12,1,41.99);
INSERT INTO object_bought VALUES('bigdaddy',to_date('2011/02/21:12:54:16PM', 'yyyy/mm/dd:hh:mi:ssam'),11,5,1,31.99);
INSERT INTO object_bought VALUES('trollolol',to_date('2009/03/01:01:12:32PM', 'yyyy/mm/dd:hh:mi:ssam'),20,2,1,20.99);

INSERT INTO object_favorite (fid, username) VALUES(1,'trollolol');
UPDATE object_favorite SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=1);
INSERT INTO object_favorite (fid, username) VALUES(2,'bigdaddy');
UPDATE object_favorite SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=5);
INSERT INTO object_favorite (fid, username) VALUES(3,'newuser');
UPDATE object_favorite SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=6);
INSERT INTO object_favorite (fid, username) VALUES(4,'friday');
UPDATE object_favorite SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=6);
INSERT INTO object_favorite (fid, username) VALUES(5,'ragingbull');
UPDATE object_favorite SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=7);
INSERT INTO object_favorite (fid, username) VALUES(6,'bigdaddy');
UPDATE object_favorite SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=15);
INSERT INTO object_favorite (fid, username) VALUES(7,'friday');
UPDATE object_favorite SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=18);
INSERT INTO object_favorite (fid, username) VALUES(8,'trollolol');
UPDATE object_favorite SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=23);
INSERT INTO object_favorite (fid, username) VALUES(9,'newuser');
UPDATE object_favorite SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=26);
INSERT INTO object_favorite (fid, username) VALUES(10,'friday');
UPDATE object_favorite SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=31);
INSERT INTO object_favorite (fid, username) VALUES(11,'ragingbull');
UPDATE object_favorite SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=39);

INSERT INTO object_write_comment (text,time,username) VALUES('Silly hats only',to_date('2010/01/23:12:00:00AM', 'yyyy/mm/dd:hh:mi:ssam'),'ninjaturtles');
UPDATE object_write_comment SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=1);
INSERT INTO object_write_comment (text,time,username) VALUES('I was hanging with the fellas',to_date('2010/05/31:12:00:00AM', 'yyyy/mm/dd:hh:mi:ssam'),'friday');
UPDATE object_write_comment SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=2);
INSERT INTO object_write_comment (text,time,username) VALUES('Saw you with your new boyfriend',to_date('2011/01/12:03:23:00PM', 'yyyy/mm/dd:hh:mi:ssam'),'bigdaddy');
UPDATE object_write_comment SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=2);
INSERT INTO object_write_comment (text,time,username) VALUES('Made me jealous',to_date('2005/05/21:04:34:20PM', 'yyyy/mm/dd:hh:mi:ssam'),'babycakes');
UPDATE object_write_comment SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=5);
INSERT INTO object_write_comment (text,time,username) VALUES('Who that is at the do',to_date('2009/08/01:02:34:35PM', 'yyyy/mm/dd:hh:mi:ssam'),'babycakes');
UPDATE object_write_comment SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=5);
INSERT INTO object_write_comment (text,time,username) VALUES('See what had happened was',to_date('2009/10/21:09:20:05PM', 'yyyy/mm/dd:hh:mi:ssam'),'trollolol');
UPDATE object_write_comment SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=6);
INSERT INTO object_write_comment (text,time,username) VALUES('Sunday comes afterwards',to_date('2010/02/20:07:00:00AM', 'yyyy/mm/dd:hh:mi:ssam'),'ninjaturtles');
UPDATE object_write_comment SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=8);
INSERT INTO object_write_comment (text,time,username) VALUES('Yesterday was Thursday Thursday.',to_date('2001/05/28:12:34:00AM', 'yyyy/mm/dd:hh:mi:ssam'),'ragingbull');
UPDATE object_write_comment SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=8);
INSERT INTO object_write_comment (text,time,username) VALUES('Today it is Friday Friday',to_date('2008/02/21:04:12:00PM', 'yyyy/mm/dd:hh:mi:ssam'),'friday');
UPDATE object_write_comment SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=3);
INSERT INTO object_write_comment (text,time,username) VALUES('We, we, we so excited we so excited',to_date('2011/03/24:11:23:11AM', 'yyyy/mm/dd:hh:mi:ssam'),'trollolol');
UPDATE object_write_comment SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=30);
INSERT INTO object_write_comment (text,time,username) VALUES('Tomorrow it is Saturday',to_date('2009/01/11:10:30:10AM', 'yyyy/mm/dd:hh:mi:ssam'),'sexytime');
UPDATE object_write_comment SET beverage=(SELECT REF(object_alcohol) FROM object_alcohol WHERE object_alcohol.did=24);

